### ISSUE TITLE
No % battery on statusbar

### ISSUE THREAD

**Issue by mtimvik** [scoute-dich/Blue-Minimal#2]
When I use statusbar from this theme the % of battery is lost from statusbar.
Checked on Nexus 5 (CyanogenMod 12.1 - Android 5.1)

**Comment by scoute-dich** [comment]
For me it is working. Using Samsung n7000 CM13.

It works with "Battery status style -> Text" and only option which doesn't work for me is "Battery status style -> Circle" + "Battery percentage -> Inside the icon". Which settings are you using?

**Comment by scoute-dich** [comment]
For me it is working. Using Samsung n7000 CM13.

It works with "Battery status style -> Text" and only option which doesn't work for me is "Battery status style -> Circle" + "Battery percentage -> Inside the icon". Which settings are you using?

**Comment by mtimvik** [comment]
I use. "Circle with Battery percentage -> Inside the icon"

**Comment by scoute-dich** [comment]
Hi,

sorry for the late response. I tested it with same settings. Battery Percentage is also disappearing on my smartphone. I tested it also with the default cyanogenmod theme. There the percentage indicator also disappears. So I think it's a cm bug. I also can't beleave that this is de fault of my theme, because I changed nothing concerning the statusbar icons...

Anyway if it's the fault of my theme I can't do anything. If you have a solution, you can report it to me... So I hope that you don't worry and still enjoy my theme.
